osmblog/blog/urls.py
from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url

from osmblog.blog import views


user_urls = patterns(
    '',

    url(
        r'^$',
        views.ArticleListView.as_view(), name='posts'
    ),
    url(
        (
            r'^(?P<year>[0-9]{4})/'
            r'(?P<month>[0-9]{1,2})/'
            r'(?P<day>[0-9]{1,2})/'
            r'(?P<slug>[-\w]+)/$'
        ),
        views.ArticleView.as_view(), name='post'
    ),
)

urlpatterns = patterns(
    '',

    url(
        r'^by-category/(?P<category_slug>[-\w]+)/$',
        views.LatestArticleListView.as_view(),
        name='by-category'
    ),
    url(
        r'^latest-posts/$',
        views.LatestArticleListView.as_view(),
        kwargs={'page_title': 'Latest Blogs'},
        name='latest-posts'
    ),
    url(
        r'^new-bloggers/$',
        views.LatestArticleListView.as_view(),
        kwargs={'page_title': 'New bloggers', 'unique_users': True},
        name='new-bloggers'
    ),

    url(r'^user/(?P<username>[-\w]+)/', include(user_urls, 'user')),
)

osmblog/urls.py
from django.conf.urls import include
from django.conf.urls import patterns
from django.conf.urls import url
from django.contrib import admin

from osmblog.site.views import HomeView

admin.autodiscover()


urlpatterns = patterns(
    '',

    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),

    url(r'^', include('osmblog.blog.urls', namespace='blog')),
)

templates/base.html
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    {% block head %}
      {% block head_meta %}
        <meta charset="utf-8">
      {% endblock %}

      {% block head_css %}{% endblock %}

      <title>{% block title %}Whistler{% endblock %}</title>
    {% endblock %}
  </head>

  <body>
    <div class="inner">
      {% block main_container %}{% endblock %}
    </div>

    {% block body_append %}{% endblock %}
  </body>
</html>

templates/base_site.html
{% extends 'base.html' %}

{% load local_site %}


{% block head_css %}
  <link rel="stylesheet" href="{{ STATIC_URL }}css/fluid24/reset.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/fluid24/fluid24.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/fluid24/text.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
{% endblock %}


{% block main_container %}
  <header>
    {% block main_header %}
      <nav>
        <div class="container_24 clearfix">
          <a href="/" class="logo"></a>

          <a href="{% url 'blog:latest-posts' %}">Latest blogs</a>
          <a href="{% url 'blog:new-bloggers' %}">New bloggers</a>

          <a class="purple-btn" href="#">Sign up for free</a>
        </div>
      </nav>

      <h1 class="container_24 clearfix">
        {% block page_title %}Blog{% endblock %}
      </h1>
    {% endblock %}
  </header>

  <div
    id="main_content"
    class="container_24 clearfix {% block main_content_class %}{% endblock %}"
  >
    {% block main_content %}
      <section id="main_column" class="grid_16">
        {% block main_column %}{% endblock %}
      </section>

      <section id="side_column" class="grid_7 prefix_1">
        {% block side_column %}
          {% display_categories %}
        {% endblock %}
      </section>
    {% endblock %}
  </div>

  <footer>
    <div class="container_24 ">
      {% block main_footer %}
        <section class="content grid_16">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin
          blandit consequat elit, ac volutpat nulla molestie quis. Morbi
          blandit nulla at turpis fermentum ultricies. Sed hendrerit ipsum
          elit, non dictum ligula tincidunt sed. Sed ac nisl sed sapien
          molestie venenatis.
        </section>

        <section class="sign grid_7 prefix_1">
          Designed & built by
          <a href="http://onespacemedia.co.uk">Onespacemedia</a>
        </section>
      {% endblock %}
      <div class="clear"></div>
    </div>
  </footer>
{% endblock %}


{% block body_append %}
  <script type="text/javascript">
    var disqus_shortname = 'example';

    (function () {
      var s = document.createElement('script'); s.async = true;
      s.type = 'text/javascript';
      s.src = '//' + disqus_shortname + '.disqus.com/count.js';
      (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
  </script>
{% endblock %}